version: '3.8'

services:
  signaling:
    build: ./signaling
    ports:
      - "9000:9000"
      - "9001:9001"

  
  gateway:
    build: ./gateway
    depends_on:
      - signaling
    environment:
      - CAMERA_RTSP_URL=rtsp://807e9439d5ca.entrypoint.cloud.wowza.com:1935/app-rC94792j/068b9c9a_stream2


  client:
    build: ./client
    ports:
      - "8080:80"